import type { ExpertProfile, MarketplaceJob, Showcase } from "./types";

export const experts: ExpertProfile[] = [
  {id:"exp_ana",slug:"ana-kovacevic",name:"Ana Kovacevic",title:"n8n Solutions Architect · AI & Revenue Ops",bio:"I design reliable n8n systems for revenue teams, AI operations and internal tooling. My focus is observability, clean handoffs and workflows your team can actually maintain.",location:"Vienna, Austria",timezone:"CET",photoUrl:"https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80",skills:["n8n","AI Agents","TypeScript","APIs"],integrations:["HubSpot","OpenAI","Slack","Postgres"],hourlyRate:95,currency:"EUR",availability:"Available this week",rating:4.98,reviewCount:37,completedProjects:44,verified:true,status:"PUBLISHED",badges:["Top Expert","Fast response"]},
  {id:"exp_luka",slug:"luka-petrovic",name:"Luka Petrovic",title:"Senior Automation Engineer · CRM & Operations",bio:"Complex n8n automations, API integrations and migrations from Zapier/Make. I work with operations teams that need durable systems rather than brittle demos.",location:"Belgrade, Serbia",timezone:"CET",photoUrl:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=320&q=80",skills:["n8n","JavaScript","Webhooks","Databases"],integrations:["Salesforce","Stripe","Google Workspace","Supabase"],hourlyRate:78,currency:"EUR",availability:"20 hrs / week",rating:4.94,reviewCount:28,completedProjects:35,verified:true,status:"PUBLISHED",badges:["API specialist"]},
  {id:"exp_maya",slug:"maya-novak",name:"Maya Novak",title:"AI Automation Developer · Support & Knowledge",bio:"I build support and knowledge automations using n8n, LLMs and retrieval pipelines, with human review and auditability built in from day one.",location:"Prague, Czechia",timezone:"CET",photoUrl:"https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=320&q=80",skills:["n8n","RAG","Python","AI Agents"],integrations:["Intercom","Notion","Qdrant","Anthropic"],hourlyRate:88,currency:"EUR",availability:"Available in 3 days",rating:5,reviewCount:19,completedProjects:24,verified:true,status:"PUBLISHED",badges:["100% success"]},
  {id:"exp_noah",slug:"noah-williams",name:"Noah Williams",title:"n8n Backend Integrations · Fintech & Data",bio:"Backend-first automation engineering for APIs, payment systems and data sync. Strong on idempotency, queues, retries and production monitoring.",location:"London, UK",timezone:"GMT",photoUrl:"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=320&q=80",skills:["n8n","Node.js","Payments","Postgres"],integrations:["Stripe","Xero","AWS","PostgreSQL"],hourlyRate:110,currency:"EUR",availability:"Next week",rating:4.97,reviewCount:31,completedProjects:39,verified:true,status:"PUBLISHED",badges:["Fintech"]}
];

export const showcases: Showcase[] = [
  {id:"s1",expertId:"exp_ana",title:"AI-qualified inbound pipeline",summary:"Lead enrichment, intent classification, CRM routing and Slack approval in one observable n8n workflow.",outcome:"Cut manual qualification time by 82%",integrations:["HubSpot","OpenAI","Slack"],complexity:"Advanced"},
  {id:"s2",expertId:"exp_ana",title:"Revenue operations control tower",summary:"Cross-system customer lifecycle sync with retry queues, alerts and reconciliation reports.",outcome:"Reduced sync incidents from weekly to near-zero",integrations:["Postgres","HubSpot","Google Sheets"],complexity:"Expert"},
  {id:"s3",expertId:"exp_luka",title:"Zapier to n8n migration",summary:"Rebuilt 67 automations with shared error handling and environment-aware credentials.",outcome:"Saved ~€2,400/month in automation costs",integrations:["Salesforce","Google Workspace","Slack"],complexity:"Expert"},
  {id:"s4",expertId:"exp_maya",title:"Support copilot with human review",summary:"RAG-backed draft replies, confidence thresholds and escalation to specialists.",outcome:"44% faster first response time",integrations:["Intercom","Qdrant","Anthropic"],complexity:"Advanced"}
];

export const jobs: MarketplaceJob[] = [
  {id:"job_101",clientId:"c1",clientName:"Northstar Commerce",title:"Rebuild our lead-to-demo automation in n8n",description:"We are moving from a mix of Zapier and custom scripts to n8n. Need lead enrichment, routing, CRM updates, calendar handoff and clear failure alerts.",skills:["n8n","APIs","JavaScript"],integrations:["HubSpot","Clay","Google Calendar"],visibility:"PUBLIC",status:"OPEN",budgetMin:2500,budgetMax:4500,currency:"EUR",delivery:"2–3 weeks",proposalCount:9,postedAt:"2 hours ago",verifiedPayment:true},
  {id:"job_102",clientId:"c2",clientName:"Atlas Legal",title:"Document intake + AI extraction workflow",description:"Build a secure intake pipeline that receives documents, classifies them, extracts structured fields and routes exceptions for human review.",skills:["n8n","AI","Security"],integrations:["Google Drive","OpenAI","Postgres"],visibility:"PUBLIC",status:"OPEN",budgetMin:4000,budgetMax:7000,currency:"EUR",delivery:"4 weeks",proposalCount:6,postedAt:"Yesterday",verifiedPayment:true},
  {id:"job_103",clientId:"c3",clientName:"Mercury Studio",title:"n8n monitoring and incident recovery setup",description:"Audit 35 production workflows and implement standardized retries, dead-letter handling, alerting and weekly health reporting.",skills:["n8n","Observability","APIs"],integrations:["Slack","Better Stack","Postgres"],visibility:"PUBLIC",status:"OPEN",budgetMin:1800,budgetMax:3200,currency:"EUR",delivery:"10 days",proposalCount:12,postedAt:"2 days ago",verifiedPayment:true}
];

export const dashboardStats=[{label:"Active contracts",value:"3",helper:"€8,600 funded"},{label:"Open jobs",value:"4",helper:"18 proposals"},{label:"Saved experts",value:"12",helper:"5 available now"},{label:"Total spent",value:"€21.4k",helper:"Across 9 contracts"}];
