import type { ExpertLink } from "@/lib/types";

/**
 * Candidates who emailed team@n8nlab.io offering automation work.
 *
 * Everything here is derived from what each person wrote in their own
 * application. Where they did not state something (rate, country, availability)
 * the field is left empty and listed in `missing` — the profile still publishes,
 * and the expert is asked to fill the gaps after claiming it.
 *
 * `email` is used only to mint the claim code and is written to a private
 * Firestore collection. It is never part of the public profile document.
 */
export interface SeedCandidate {
  id: string;
  slug: string;
  name: string;
  email: string;
  title: string;
  bio: string;
  location: string;
  country: string;
  timezone: string;
  skills: string[];
  integrations: string[];
  hourlyRate: number;
  availability: string;
  links: ExpertLink[];
  /** Source documents already on file, uploaded from the application mailbox. */
  documents: string[];
  missing: string[];
}

const M_RATE = "hourlyRate";
const M_LOC = "location";
const M_AVAIL = "availability";
const M_BIO = "bio";
const M_PHOTO = "photo";
const M_SKILLS = "skills";

export const seedCandidates: SeedCandidate[] = [
  {
    id: "cand_ahsan_salman",
    slug: "ahsan-salman",
    name: "Ahsan Salman",
    email: "ahsansalman1234@gmail.com",
    title: "AI Automation Developer",
    bio: "Applied for AI automation work with a CV on file. Detailed background, stack and project history still to be added by the expert.",
    location: "",
    country: "",
    timezone: "",
    skills: ["n8n", "AI Automation"],
    integrations: [],
    hourlyRate: 0,
    availability: "",
    links: [],
    documents: ["Ahsan_Salman_Resume_AI.pdf"],
    missing: [M_BIO, M_LOC, M_RATE, M_AVAIL, M_SKILLS, M_PHOTO],
  },
  {
    id: "cand_jason_givati",
    slug: "jason-givati",
    name: "Jason Givati",
    email: "JJ@nightshiftanswers.com",
    title: "n8n Reliability Engineer · Auditing & Monitoring",
    bio: "I work on the failure mode most monitoring misses: the run that completes, reports success, and produced nothing. No exception is thrown, so nothing in the error handling fires. I audit for it by reading execution history from outside the instance, which catches what reviewing the workflow cannot — on 2.36.7 a node on a branch whose condition stops matching is absent from the run data entirely while the execution still returns success.",
    location: "",
    country: "",
    timezone: "",
    skills: ["n8n", "Execution auditing", "Error handling", "Monitoring"],
    integrations: [],
    hourlyRate: 0,
    availability: "Fixed-fee audits",
    links: [
      { label: "Audit report sample", url: "https://ranfine.io/audit" },
      { label: "Website", url: "https://ranfine.io" },
    ],
    documents: [],
    missing: [M_LOC, M_RATE, M_PHOTO],
  },
  {
    id: "cand_mahdi_jellali",
    slug: "mahdi-jellali",
    name: "Mahdi Jellali",
    email: "mahdio.jellali@hotmail.fr",
    title: "AI Automation Developer",
    bio: "Applied through LinkedIn with a 2026 CV on file. Detailed background, stack and project history still to be added by the expert.",
    location: "",
    country: "",
    timezone: "",
    skills: ["n8n", "AI Automation"],
    integrations: [],
    hourlyRate: 0,
    availability: "",
    links: [],
    documents: ["Mahdi_Resume_2026.pdf"],
    missing: [M_BIO, M_LOC, M_RATE, M_AVAIL, M_SKILLS, M_PHOTO],
  },
  {
    id: "cand_muhammad_ahmed",
    slug: "muhammad-ahmed",
    name: "Muhammad Ahmed",
    email: "muhammad.ahmedtn1@gmail.com",
    title: "Automation & Integration Developer",
    bio: "Four-plus years in Zoho development, workflow and business process automation, API integrations, webhooks and Deluge scripting. Works on connecting business systems end to end rather than one-off scripts.",
    location: "",
    country: "",
    timezone: "",
    skills: ["Workflow automation", "API integration", "Webhooks", "Deluge"],
    integrations: ["Zoho"],
    hourlyRate: 0,
    availability: "",
    links: [],
    documents: ["Muhammad_Ahmed_CV.pdf"],
    missing: [M_LOC, M_RATE, M_AVAIL, M_PHOTO],
  },
  {
    id: "cand_altamash_sahibole",
    slug: "altamash-sahibole",
    name: "Altamash Sahibole",
    email: "asahibole10@gmail.com",
    title: "AI Engineer · LLM, RAG & Agents",
    bio: "Works in AI and generative AI engineering: Python, LLMs, retrieval-augmented generation, LangChain and LangGraph, FastAPI, MongoDB and vector databases, building AI-based applications.",
    location: "",
    country: "",
    timezone: "",
    skills: ["Python", "LLMs", "RAG", "LangChain", "LangGraph", "FastAPI"],
    integrations: ["MongoDB", "Vector databases"],
    hourlyRate: 0,
    availability: "",
    links: [],
    documents: [],
    missing: [M_LOC, M_RATE, M_AVAIL, M_PHOTO],
  },
  {
    id: "cand_philemon_firone",
    slug: "philemon-firone",
    name: "Philemon Firone",
    email: "fironeautomations@gmail.com",
    title: "AI Automation Builder · Lead Gen & CRM",
    bio: "Hands-on AI automation builder using n8n, LLMs, APIs, webhooks and JavaScript. Builds workflows for lead generation, outreach, qualification and CRM automation.",
    location: "Nigeria",
    country: "Nigeria",
    timezone: "WAT",
    skills: ["n8n", "LLMs", "APIs", "Webhooks", "JavaScript"],
    integrations: ["CRM"],
    hourlyRate: 0,
    availability: "",
    links: [],
    documents: [],
    missing: [M_RATE, M_AVAIL, M_PHOTO],
  },
  {
    id: "cand_kirill_brueggemann",
    slug: "kirill-brueggemann",
    name: "Kirill Brüggemann",
    email: "kontakt@kibrueg.de",
    title: "AI Automation Engineer · n8n & LLM Integration",
    bio: "Freelance AI automation engineer focused on n8n and LLM integration. Twelve-plus production workflows covering scrapers, parsers, API integrations, error handling and Telegram bots. Portfolio highlight is JobRadar, a fully automated job-analysis system on n8n running 80+ sources and 2,400+ postings a month with AI-assisted matching, taken from architecture through to production deployment on a VPS. German (C1), English (B2), Russian (native).",
    location: "Germany",
    country: "Germany",
    timezone: "CET",
    skills: ["n8n", "Python", "Prompt engineering", "RAG", "Docker", "Webhook design"],
    integrations: ["OpenRouter", "Qwen3", "Postgres", "Telegram", "REST APIs"],
    hourlyRate: 0,
    availability: "Available for subcontracting",
    links: [
      { label: "GitHub", url: "https://github.com/KiBrueg" },
      { label: "LinkedIn", url: "https://linkedin.com/in/kirill-bruggemann" },
    ],
    documents: [
      "Lebenslauf_Kirill_Brueggemann_KiAutomation_DE_korrigiert.pdf",
      "AI_Automation_Portfolio_Working_Build_Full_En_compressed.pdf",
      "jobradar-angebot.pdf",
    ],
    missing: [M_RATE, M_PHOTO],
  },
  {
    id: "cand_oduwole_adetola",
    slug: "faruq-oduwole",
    name: "Oduwole Faruq Adetola",
    email: "oduwoleadetohlar@gmail.com",
    title: "AI Automation Engineer",
    bio: "AI automation engineer building n8n workflows from lead intake and AI-assisted scoring through to error handling and audit logging. Published an end-to-end real estate lead automation: webhook intake, validation, property enrichment via the SimplyRETS API, AI-assisted matching with an OpenAI fallback, rule-based Hot/Warm/Cold scoring, and routing into Slack alerts, Airtable CRM records and multi-step email follow-ups, with a centralised error-trigger workflow logging failures to Airtable. Also built a live forex and gold signal pipeline with AI-assisted analysis delivered over Telegram.",
    location: "Nigeria",
    country: "Nigeria",
    timezone: "WAT",
    skills: ["n8n", "Webhooks", "REST APIs", "JavaScript", "Error handling"],
    integrations: ["OpenAI", "Airtable", "Slack", "SimplyRETS", "Telegram"],
    hourlyRate: 0,
    availability: "",
    links: [{ label: "GitHub", url: "https://github.com/TolaAutomate" }],
    documents: ["Faruq_Oduwole_AI_Automation_Engineer_CV.pdf"],
    missing: [M_RATE, M_AVAIL, M_PHOTO],
  },
  {
    id: "cand_uthman_adesola",
    slug: "uthman-adesola",
    name: "Uthman Adesola",
    email: "uthmanadesola12@gmail.com",
    title: "AI Automation Specialist · Voice Agents",
    bio: "Builds AI voice agents on Retell.ai, Vapi and Voiceflow alongside workflow automation in n8n, Make.com and Zapier. Delivered a multi-platform social media automation system with RSS-triggered content pipelines, AI-generated captions and images via OpenAI, scheduled multi-platform publishing and Airtable-driven CRM automation. Integrates GPT models, CRMs and telephony via Twilio into production automations.",
    location: "Nigeria",
    country: "Nigeria",
    timezone: "WAT",
    skills: ["n8n", "Voice AI", "Make.com", "Zapier", "AI agents"],
    integrations: ["Retell.ai", "Vapi", "Voiceflow", "OpenAI", "Twilio", "Airtable"],
    hourlyRate: 0,
    availability: "",
    links: [],
    documents: ["UTHMAN ADESOLA CV.pdf"],
    missing: [M_RATE, M_AVAIL, M_PHOTO],
  },
  {
    id: "cand_jeremy_taverne",
    slug: "jeremy-taverne",
    name: "Jérémy Taverne",
    email: "essac92@gmail.com",
    title: "AI Automation Developer · n8n & OpenAI",
    bio: "Has delivered several automation projects with n8n and OpenAI, optimising workflows for a range of needs. Applied for an apprenticeship (alternance) position; CV and mission sheet on file.",
    location: "France",
    country: "France",
    timezone: "CET",
    skills: ["n8n", "OpenAI", "Workflow optimisation"],
    integrations: ["OpenAI"],
    hourlyRate: 0,
    availability: "Apprenticeship / alternance",
    links: [],
    documents: ["CV_Taverne_Jeremy.pdf", "Fiche_Mission_Taverne_Jeremy_2.pdf"],
    missing: [M_RATE, M_PHOTO],
  },
  {
    id: "cand_yaroslav",
    slug: "yaroslav-n8n",
    name: "Yaroslav",
    email: "popapopav042@gmail.com",
    title: "Junior n8n Developer",
    bio: "Early-career n8n developer looking for paid project-based or overflow work. Strongest on Google Sheets, Forms, Gmail and Calendar, lead qualification, routing, status handling, notifications, basic JavaScript, webhooks and smaller API integrations. Four self-directed n8n projects in the portfolio; no paid client deployments yet, so specifically interested in starting with a small, well-defined paid task. Prefers asynchronous written communication.",
    location: "",
    country: "",
    timezone: "",
    skills: ["n8n", "JavaScript", "Webhooks", "Lead qualification"],
    integrations: ["Google Sheets", "Google Forms", "Gmail", "Google Calendar"],
    hourlyRate: 0,
    availability: "Project-based / overflow",
    links: [{ label: "Portfolio", url: "https://github.com/vaximiliar/n8n-automation-portfolio" }],
    documents: [],
    missing: [M_LOC, M_RATE, M_PHOTO],
  },
  {
    id: "cand_victor_laybats",
    slug: "victor-laybats",
    name: "Victor Laybats",
    email: "contact@victorlaybats.com",
    title: "Solo Builder · Autonomous AI Agents",
    bio: "Solo builder shipping and operating nine live AI-agent products alone. Builds autonomous agents that run unattended in production on Node and Python, with self-hosted Postgres and Supabase on Docker, live billing and multi-provider LLM routing. Owns the full stack and can take a client agent build end to end.",
    location: "Remote",
    country: "",
    timezone: "",
    skills: ["AI agents", "Node.js", "Python", "Docker", "LLM routing"],
    integrations: ["Postgres", "Supabase"],
    hourlyRate: 0,
    availability: "Available now",
    links: [{ label: "Portfolio", url: "https://victorlaybats.com" }],
    documents: [],
    missing: [M_LOC, M_RATE, M_PHOTO],
  },
  {
    id: "cand_umair_imran",
    slug: "umair-imran",
    name: "Umair Imran",
    email: "umairimran54321@gmail.com",
    title: "AI Automation Developer · n8n & Voice AI",
    bio: "AI automation developer focused on n8n, AI agents, API integrations, webhooks and voice AI. Recently built an AI voice grocery-store automation system using ElevenLabs, n8n, Google Sheets and AI agents, handling new orders, inventory checks, order updates, inquiries and complaints through voice. Available 40 hours a week and able to start immediately.",
    location: "",
    country: "",
    timezone: "",
    skills: ["n8n", "AI agents", "Voice AI", "APIs", "Webhooks"],
    integrations: ["ElevenLabs", "Google Sheets"],
    hourlyRate: 0,
    availability: "40 hrs / week",
    links: [
      { label: "GitHub", url: "https://github.com/umairimran54321" },
      { label: "LinkedIn", url: "https://www.linkedin.com/in/umair-imran-4a6454419/" },
    ],
    documents: ["UMAIR IMRAN RESUME.pdf"],
    missing: [M_LOC, M_RATE, M_PHOTO],
  },
  {
    id: "cand_nolan_welsh",
    slug: "nolan-welsh",
    name: "Nolan Welsh",
    email: "nolan@welshsystems.io",
    title: "Automation Engineer · Production n8n & Infrastructure",
    bio: "Automation engineer building production systems in n8n along with the APIs, databases and infrastructure behind them, and managing the infrastructure those systems run on. Has worked across CRM and sales automation, e-commerce, financial operations, AI workflows and internal tooling. Trades as Welsh Systems and is taking on additional contract and overflow work.",
    location: "Canada",
    country: "Canada",
    timezone: "",
    skills: ["n8n", "APIs", "Databases", "Infrastructure"],
    integrations: ["CRM", "E-commerce"],
    hourlyRate: 0,
    availability: "Contract / overflow",
    links: [{ label: "LinkedIn", url: "https://www.linkedin.com/in/nolanwelsh" }],
    documents: [],
    missing: [M_RATE, M_PHOTO],
  },
  {
    id: "cand_ilyess_allen",
    slug: "ilyess-allen",
    name: "Ilyess Allen",
    email: "ilyessallen.ai@gmail.com",
    title: "AI & Automation Consultant",
    bio: "Builds production systems for businesses: CRM automation, AI agents and workflow tools using Make, Airtable, GPT-4 and Claude. Interested in freelance collaboration and subcontracted project work, with a focus on the London market. Open to relocation or remote collaboration.",
    location: "London / France",
    country: "United Kingdom",
    timezone: "CET",
    skills: ["AI agents", "CRM automation", "Workflow tools"],
    integrations: ["Make", "Airtable", "GPT-4", "Claude"],
    hourlyRate: 0,
    availability: "Open to freelance",
    links: [{ label: "Website", url: "https://ilyess-ai-consultent.lovable.app/" }],
    documents: [],
    missing: [M_RATE, M_PHOTO],
  },
  {
    id: "cand_automation_note",
    slug: "automation-note",
    name: "Automation Note",
    email: "info@rains-it.com",
    title: "Independent Practice · n8n Delivery & QA",
    bio: "An independent Japan-based practice focused on reliable n8n and Make implementation, API and webhook integrations, troubleshooting and written handoff. Works as an additional async delivery or QA layer behind existing client work, in bounded slices: one workflow up to eight main steps, implementation or failure-path review, retry and idempotency checks, synthetic or redacted data first, and a short written handoff. No client-facing calls or production credentials required for initial evaluation.",
    location: "Japan",
    country: "Japan",
    timezone: "JST",
    skills: ["n8n", "Make", "QA", "Idempotency", "Documentation"],
    integrations: ["REST APIs", "Webhooks"],
    hourlyRate: 0,
    availability: "Async delivery slices",
    links: [
      { label: "Portfolio", url: "https://automation-note.com/articles/n8n-inquiry-routing-portfolio/" },
      { label: "Agency overflow", url: "https://automation-note.com/services/n8n-agency-overflow/" },
    ],
    documents: [],
    missing: [M_RATE, M_PHOTO],
  },
  {
    id: "cand_daniil_baranok",
    slug: "daniil-baranok",
    name: "Daniil Baranok",
    email: "daniilbaranok@gmail.com",
    title: "Junior n8n Engineer · AI Agents",
    bio: "Built and runs DacherForge, a production AI SDR agent: Make.com orchestration, Telegram and VK bots, OpenAI and Anthropic APIs, SQL reporting and a Python licensing microservice, self-hosted on a Linux VPS with Docker and Cloudflare tunnels. Confident with Make, working n8n knowledge, comfortable with webhooks, REST, JSON and API docs. Offers junior overflow capacity — documentation, testing and the repetitive-but-critical workflow parts. 25–30 hours a week at UTC+5 with full EU overlap.",
    location: "UTC+5",
    country: "",
    timezone: "UTC+5",
    skills: ["n8n", "Make.com", "Python", "Docker", "SQL", "Webhooks"],
    integrations: ["OpenAI", "Anthropic", "Telegram", "VK"],
    hourlyRate: 0,
    availability: "25–30 hrs / week",
    links: [],
    documents: [],
    missing: [M_LOC, M_RATE, M_PHOTO],
  },
  {
    id: "cand_farhan_ali",
    slug: "farhan-ali",
    name: "Farhan Ali",
    email: "itsfarhanali46@gmail.com",
    title: "CRM & AI Automation Specialist",
    bio: "Specialises in AI-powered workflow automation, CRM implementation and system integrations using n8n, Make.com, Zapier, Monday.com and other automation platforms. Available for collaboration on automation workflows, custom integrations and AI-driven process optimisation.",
    location: "",
    country: "",
    timezone: "",
    skills: ["n8n", "Make.com", "Zapier", "CRM implementation", "System integration"],
    integrations: ["Monday.com"],
    hourlyRate: 0,
    availability: "",
    links: [{ label: "Portfolio", url: "https://app.notion.com/p/Make-com-Expert-840bb4bbbc7482258c2781b3301fa7a6" }],
    documents: [],
    missing: [M_LOC, M_RATE, M_AVAIL, M_PHOTO],
  },
  {
    id: "cand_king_cheung",
    slug: "king-cheung",
    name: "King Cheung",
    email: "kingcheung.dev@gmail.com",
    title: "n8n & LLM Automation Engineer",
    bio: "Builds n8n and LLM automation, working as overflow capacity for agencies rather than chasing direct clients. Recent production work: an n8n and LLM check-in and reporting agent where every integration sits behind a config-swappable adapter, with a review queue for uncertain output and a dead-letter path for failed sends. Also delivered a live Twilio WhatsApp number cutover with no dropped inbound messages, plus OAuth and webhook auth, Postgres and Google Workspace integrations. 15 hours a week, UK based.",
    location: "United Kingdom",
    country: "United Kingdom",
    timezone: "GMT",
    skills: ["n8n", "LLMs", "OAuth", "Webhook auth", "Dead-letter handling"],
    integrations: ["Twilio", "Postgres", "Google Workspace", "WhatsApp"],
    hourlyRate: 0,
    availability: "15 hrs / week",
    links: [{ label: "Demo (Loom)", url: "https://www.loom.com/share/c641066fc4f64a70872ce85cfd388922" }],
    documents: [],
    missing: [M_RATE, M_PHOTO],
  },
  {
    id: "cand_ari_fairline",
    slug: "fairline-works",
    name: "Ari — Fairline Works",
    email: "fairlineworks@gmail.com",
    title: "Delivery Capacity · n8n Implementation & QA",
    bio: "Fairline Works takes on contained delivery slices when a team needs implementation capacity: an approved n8n workflow, API or webhook integration, a QA pass, or concise handover documentation using the client's authorised systems. Work stays bounded to a fixed acceptance check rather than an open-ended retainer.",
    location: "India",
    country: "India",
    timezone: "IST",
    skills: ["n8n", "QA", "Handover documentation"],
    integrations: ["REST APIs", "Webhooks"],
    hourlyRate: 0,
    availability: "Fixed-scope slices",
    links: [],
    documents: [],
    missing: [M_RATE, M_PHOTO],
  },
  {
    id: "cand_salih_uslucan",
    slug: "salih-ibrahim-uslucan",
    name: "Salih Ibrahim Uslucan",
    email: "salihibrahimuslucan2021@gmail.com",
    title: "CAD & Industrial Integration Engineer",
    bio: "Builds the parts of automation projects that touch real hardware and real CAD output. Shipped a Python engine that turns a component netlist into rule-checked, manufacturing-ready electrical panel drawings — deterministic DWG/DXF with automated regression tests — and an open-source LLM tool-use and RAG microservice stack on FastAPI, Dockerised, with Postgres and pgvector.",
    location: "",
    country: "",
    timezone: "",
    skills: ["Python", "CAD automation", "FastAPI", "RAG", "Docker"],
    integrations: ["Postgres", "pgvector", "DWG/DXF"],
    hourlyRate: 0,
    availability: "Open to trial task",
    links: [{ label: "Portfolio", url: "https://salihibrahimuslucan.github.io" }],
    documents: ["Salih_Ibrahim_Uslucan_CV.pdf"],
    missing: [M_LOC, M_RATE, M_PHOTO],
  },
  {
    id: "cand_ahmad_siddiqui",
    slug: "ahmad-siddiqui",
    name: "Ahmad Siddiqui",
    email: "ahmadsidd4191620@gmail.com",
    title: "AI Automation Consultant",
    bio: "Recently built a multi-tenant dashboard for a client with Supabase as the data layer, n8n running all the backend automation and a Claude-powered interface on top. Alongside that, builds voice agents and chatbots tailored to specific client workflows.",
    location: "",
    country: "",
    timezone: "",
    skills: ["n8n", "AI agents", "Voice agents", "Chatbots"],
    integrations: ["Supabase", "Claude"],
    hourlyRate: 0,
    availability: "",
    links: [{ label: "LinkedIn", url: "https://www.linkedin.com/in/sidddidit" }],
    documents: [],
    missing: [M_LOC, M_RATE, M_AVAIL, M_PHOTO],
  },
  {
    id: "cand_herry_choudhary",
    slug: "herry-choudhary",
    name: "Herry Choudhary",
    email: "herrychoudhary@cloudrockethq.com",
    title: "Automation Agency · Bounded Overflow Builds",
    bio: "Runs a one-person AI automation agency in India, taking on bounded overflow builds in n8n, Make, Zapier and Airtable when another team is full. Works to a fixed scope agreed upfront — proposed deliverables, exclusions and required access stated before either side commits — with handoff five business days after the scope, access and start date are agreed. Written-first and async, calls available when useful. The client relationship stays with the agency that brought the work.",
    location: "India",
    country: "India",
    timezone: "IST",
    skills: ["n8n", "Make", "Zapier", "Airtable", "Scoped delivery"],
    integrations: ["Airtable"],
    hourlyRate: 0,
    availability: "One bounded build at a time",
    links: [],
    documents: [],
    missing: [M_RATE, M_PHOTO],
  },
  {
    id: "cand_himani",
    slug: "himani",
    name: "Himani",
    email: "h.nprasad068@gmail.com",
    title: "Full-Stack Software Engineer · Backend & Distributed Systems",
    bio: "Full-stack software engineer with four-plus years and a strong backend focus, previously at Uber, Deliveroo and Ximkart. Has built and owned end-to-end product features across React frontends, scalable backend services, distributed systems and data-intensive platforms using Java, Go, Kafka, AWS, Python and Terraform. Work includes migrating critical workflows to event-driven architectures, building reliable streaming services, and resolving production issues to improve reliability and processing performance.",
    location: "",
    country: "",
    timezone: "",
    skills: ["Java", "Go", "Python", "Kafka", "Terraform", "Distributed systems"],
    integrations: ["AWS", "React"],
    hourlyRate: 0,
    availability: "Available now",
    links: [],
    documents: [],
    missing: [M_LOC, M_RATE, M_PHOTO],
  },
  {
    id: "cand_krish_parmar",
    slug: "krish-parmar",
    name: "Krish Parmar",
    email: "krishparmar003@gmail.com",
    title: "ML & AI Engineer · LLMs and Agentic Workflows",
    bio: "Final-year student at NIT Surat with more than two years of hands-on experience across ML and AI, working with LLMs, agentic workflows and automation. Remote-ready, comfortable across multiple time zones and available long-term.",
    location: "Surat, India",
    country: "India",
    timezone: "IST",
    skills: ["Machine learning", "LLMs", "Agentic workflows", "Automation"],
    integrations: [],
    hourlyRate: 0,
    availability: "Available long-term",
    links: [{ label: "Portfolio", url: "https://krishparmar003.github.io" }],
    documents: [],
    missing: [M_RATE, M_PHOTO],
  },
  {
    id: "cand_sai_guttikonda",
    slug: "sai-srinivas-guttikonda",
    name: "Sai Srinivas Guttikonda",
    email: "sai.gs@outlook.com",
    title: "Computer Science Graduate",
    bio: "Recent MS in Computer Science graduate from George Washington University. Applied with a resume; detailed background, stack and project history still to be added by the expert.",
    location: "",
    country: "",
    timezone: "",
    skills: [],
    integrations: [],
    hourlyRate: 0,
    availability: "",
    links: [],
    documents: [],
    missing: [M_BIO, M_LOC, M_RATE, M_AVAIL, M_SKILLS, M_PHOTO],
  },
];
